pip install --upgrade pip;
pip install torch==1.7.0 torchvision==0.8.1;
pip install timm==0.3.2;
pip install einops;
pip install torchprofile;
pip install tensorboardX;
pip install cupy-cuda100;
pip install addict;
pip install yapf;
pip install cython;
pip install scikit-build;
pip install opencv-python;
pip install pytest-runner;
pip install terminaltables==3.1.0;
pip install mmpycocotools;